version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=nakama
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - data:/var/lib/postgres/data
        expose:
            - "8080"
            - "5432"
        ports:
            - "5432:5432"
            - "8080:8080"
    nakama:
        container_name: nakama
        image: registry.heroiclabs.com/heroiclabs/nakama:3.14.0
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - >
                /nakama/nakama migrate up --database.address postgres:${POSTGRES_PASSWORD}@postgres:5432/nakama &&
                exec /nakama/nakama --name nakama1 --database.address postgres:${POSTGRES_PASSWORD}@postgres:5432/nakama --logger.level INFO --session.token_expiry_sec 7200
        restart: always
        links:
            - "postgres:db"
        depends_on:
            - postgres
        volumes:
            - ./:/nakama/data
        expose:
            - "7349"
            - "7350"
            - "7351"
        ports:
            - "7349:7349"
            - "7350:7350"
            - "7351:7351"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:7350/"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    data:
